kursach/urls.py
from django.contrib import admin
from django.urls import path
from onec import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name="main"),

    path('login/', auth_views.LoginView.as_view(), name="login"),
    path('logout/', auth_views.LogoutView.as_view(), name="logout"),
    path('reg/', views.sign_up, name="reg"),

    path('guide/', views.spravochnik, name="spravochnik"),
    path('modul/', views.modul, name='modul'),
    path('cong/', views.cong, name='cong'),

    path('profile/', views.profile, name="profile"),
    path('edit/', views.edit, name="edit"),
    path('onec_special/', views.ex, name="onec_special"),
    path('onec/', views.onec, name='onec'),
]

onec/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    first_name = models.CharField(default='Лошадка', max_length=100)
    last_name = models.CharField(default='Таинственная', max_length=100)
    age = models.IntegerField(default=0)
    work = models.CharField(default='', max_length=200)
    special = models.CharField(default='', max_length=200)
    status = models.CharField(default='', max_length=100)

onec/forms.py
from django import forms


class SignInForm(forms.Form):
    user_name = forms.CharField(label="Login", widget=forms.TextInput(attrs={'class': 'form-control open-sans-500', 'id': 'username'}))
    user_email = forms.EmailField(label="Email", widget=forms.TextInput(attrs={'class': 'form-control open-sans-500', 'id': 'email'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control open-sans-500', 'id': 'psw'}), label="Password")
    password_conf = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control open-sans-500', 'id': 'psw_c'}),
                                    label="Confirm password")

onec/views.py
from django.shortcuts import render
from onec.forms import SignInForm
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect
from django.contrib.auth import authenticate, login
from onec.models import UserProfile
from django.contrib.auth.decorators import login_required

# Create your views here.
def index(request):
    context = {}
    if not request.user.is_anonymous:
        context['User'] = request.user
        

    return render(request, 'main_page.html', context)

def spravochnik(request):
    context = {}

    if not request.user.is_anonymous:
        context['User'] = request.user

    table_l = [{'text': 'Общие', 'name': 'ob'}, {'text': 'Константы', 'name': 'const'}, {'text': 'Справочники', 'name': 'spr'}, \
               {'text': 'Документы', 'name': 'doc'}, {'text': 'Перечисления', 'name': 'per'}, {'text': 'Отчеты', 'name': 'otch'}, \
                {'text': 'Обработки', 'name': 'obr'}, {'text': 'Регистры', 'name': 'reg'}]
    context['table_l'] = table_l
    context['active'] = 'ob'

    table_r = [
        {'name':'ob', 'text': ['Вкладка «Общие» в конфигураторе 1С позволяет настроить параметры, связанные с общими объектами конфигурации.', 'На этой вкладке описываются такие объекты, как подсистемы, общие модули, параметры сеанса, роли, планы обмена, критерии отбора, общие формы, интерфейсы, общие макеты, общие картинки, стили, языки.', 'Эти объекты предназначены для установки правил работы пользователей с данными, для описания вспомогательных объектов, используемых для формирования различных форм, в механизме обмена данными, а также содержат общие модули и макеты, доступные из любого модуля конфигурации.', 'Кроме того, на закладке «Общие» указывается, нужно ли только создавать объекты управляемого приложения или следует создавать объекты, которые есть и в обычном приложении.']},  
        {'name':'const', 'text': ["Константы в 1С — это прикладные объекты конфигурации, которые позволяют хранить в информационной базе данные, которые не изменяются во времени или изменяются очень редко.", "Одна константа хранит одно значение. Например, в константе может храниться наименование организации, её УНП (ИНН), дата регистрации и другая информация.", "В константах 1С 8.3 можно хранить значение по умолчанию (название организации, основную валюту, единицы измерения, данные для обновления в типовых конфигурациях, настройки программы 1С).", "Чтобы добавить константу в конфигурацию, необходимо открыть дерево объектов метаданных, выделить узел «Константы» и нажать кнопку «ins» или можно добавить с помощью контекстного меню при помощи мыши."]},
        {'name':'spr', 'text': ['Справочники в 1С — это прикладные объекты конфигурации, позволяющие хранить в информационной базе данные, имеющие одинаковую структуру и списочный характер.', 'В справочниках могут храниться, например, списки сотрудников, перечень товаров, список поставщиков или покупателей.', 'Справочники наполняются самостоятельно компанией и используются в соответствии с видом деятельности и потребностями.']},
        {'name': 'doc', 'text': ['Документы в 1С — это объекты конфигурации, которые позволяют хранить информацию о совершённых хозяйственных операциях или о событиях, произошедших на предприятии.', 'Это могут быть, например, приходные накладные, приказы о приёме на работу, счета, платёжные поручения и т. д.', 'Структура документа включает:', '·Реквизиты (номер, дата, время создания документа, данные о поставщике).', '·Табличную часть (информация о товаре, сумме сделки, складе, на который приходуется продукция)', '·Строку для комментария', 'Каждому документу система автоматически присваивает порядковый номер, дату и время создания. Это позволяет установить строгую временную последовательность совершения операций.']},
        {'name': 'per', 'text': ['Перечисления в 1С — это объекты конфигурации, которые содержат в себе постоянные значения, не изменяемые в процессе работы с программой.', 'Они задаются на этапе конфигурирования, и их нельзя менять пользователю во время работы программы.', 'Перечисления используются, чтобы хранить в информационной базе 1С фиксированный список значений, который не изменяется в процессе работы пользователей.']},
        {'name': 'otch', 'text': ['Отчёты в 1С — это прикладные объекты конфигурации, предназначенные для обработки накопленной информации и получения сводных данных в удобном для просмотра и анализа виде.', 'С их помощью можно создавать документы, отражающие показатели по всем направлениям деятельности организации.', 'Также в 1С предусмотрен набор типовых отчётов для бухгалтерского учёта, например: оборотно-сальдовая ведомость, шахматная ведомость, оборотно-сальдовая ведомость по счёту и другие.']},
        {'name': 'obr', 'text': ['Обработки в 1С — это специальные объекты конфигурации, предназначенные для изменения информации в базе данных или создания нового функционала для администратора или пользователей.', 'Они способствуют автоматизации и ускорению выполнения рутинных задач.', 'Условно обработки 1С можно разделить на две группы:', '1. Вспомогательные (встроенные). Используются для автоматизации небольших участков работы программистами 1С. Могут быть выведены как дополнительные интерфейсные решения (рабочий стол пользователя, обзор конфигурации), либо как часть функционала конфигурации (начальное заполнение базы данных, закрытие месяца).', '2. Внешние обработки. Это обработки, которые не входят в состав прикладного решения и не привязаны к конкретной конфигурации. Такие обработки можно использовать в решениях без изменения их структуры.', 'С помощью обработок можно, например, удалять из системы устаревшие данные, импортировать информацию из других систем и многое другое.']},
        {'name': 'reg', 'text': ['Регистры в 1С — это таблицы для накопления оперативных данных и получения сводной информации. Данные в регистры добавляются только при проведении документов.', 'Регистры подразделяются на четыре вида:', '1. Регистры сведений. Самый простой вид регистра, ресурс которого может иметь как числовые значения, так и другой тип данных. Примеры регистров сведений: курсы валют, учётная политика, размер базовой величины и др.', '2. Регистры накопления. Имеют два подвида — «Остатки» и «Обороты», которые предназначены для разных целей. Регистр накопления «Остатки» используется для получения информации о состоянии «на момент времени», а «Обороты» — информации о данных «за период». Примеры регистров накопления: товары на складах, денежные средства, взаиморасчёты с контрагентами.', '3. Регистры бухгалтерии. Предназначены для систематизации данных о бухгалтерских проводках, которые обязательно должны быть связаны со специальным объектом «План счетов». Примеры регистров бухгалтерии: журнал проводок бухгалтерского учёта, журнал проводок управленческого учёта.', '4. Регистры расчётов. Имеют самую сложную структуру и используются для реализации сложных периодических расчётов. В конфигурациях 1С — это, в первую очередь, расчёты заработной платы и других выплат сотрудникам. Примеры регистров расчёта: начисления, удержания.']}
    ]

    context['table_r'] = table_r

    return render(request, 'spravochnik.html', context)

def modul(request):
    context = {}

    if not request.user.is_anonymous:
        context['User'] = request.user

    return render(request, 'modul.html', context)


def sign_up(request):
    context = {}

    if not request.user.is_anonymous:
        return HttpResponseRedirect('/')

    context['title'] = 'Регистрация'
    context['errors'] = []

    if request.method == 'POST':
        f = SignInForm(request.POST)

        if f.is_valid():
            u_n = f.data['user_name']
            u_em = f.data['user_email']
            u_pw = f.data['password']
            u_pw_c = f.data['password_conf']

            if not is_existing_user(User.objects.all(), u_n):
                if u_pw == u_pw_c:
                    new_user = User.objects.create_user(username=u_n, email=u_em, password=u_pw)
                    new_user.save()
                    userProfile = UserProfile.objects.create(user=new_user, status="None")
                    userProfile.save()
                    login_user = authenticate(username=u_n, password=u_pw)
                    login(request, login_user)
                    return HttpResponseRedirect('/cong/')
                else:
                    context['errors'].append("Введенные пароли не совпадают")
            else:
                context['errors'].append("Пользователь с таким логином уже существует")

            context['form'] = f
        else:
            context['form'] = f
    else:
        f = SignInForm()
        context['form'] = f

    return render(request, 'registration/reg.html', context)


def cong(request):
    context = {}

    if not request.user.is_anonymous:
        context['User'] = request.user



    return render(request, 'cong.html', context)


def profile(request):
    context = {}

    if not request.user.is_anonymous:
        context['User'] = request.user

    user = UserProfile.objects.get(user=request.user)
    context['User2'] = user

    return render(request, 'profile.html', context)

@login_required
def edit(request):
    context = {}
    context['errors'] = []

    if not request.user.is_anonymous:
        context['User'] = request.user

    user = UserProfile.objects.get(user=request.user)
    context['User2'] = user

    if request.method == "POST":
        if request.POST.get('username') == user.user.username:
            e = request.POST.get('email')
            f_n = request.POST.get('first_name')
            l_n = request.POST.get('last_name')
            ae = request.POST.get('age')
            w = request.POST.get('work')
            s = request.POST.get('special')

            request.user.email = e
            request.user.save()
            user.first_name = f_n
            user.last_name = l_n
            user.age = ae
            user.work = w
            user.special = s

onec/templates/cong.html
{% extends 'index.html' %}

{% block content %}

<div class="content">
    <div class="body">
        <div class="zag open-sans-600">
            Регистрация выполнена успешно
        </div>
        <div class="cong">
            <p class="open-sans-600">Здравствуйте, {{ User }}!</p>

            <div class="info open-sans-500">
                Вы можете перейти в <a href="{% url 'profile' %}" class="link_text">Личный кабинет</a> и настроить свой профиль или приступить к подготовке сдачи экзамена <a href="{% url 'onec_special' %}" class="link_text">1С:Специалист</a>. 
            </div>
        </div>
    </div>
</div>

{% endblock %}

onec/templates/edit_profile.html
{% extends 'index.html' %}

{% block content %}
    <div class="container">
        <form method="post">
            {% csrf_token %}
            <div class="form">
                {% for error in errors %}
                    <span class="btn btn-danger open-sans-600   ">{{ error }}</span>
                {% endfor %}

                {% if form.errors %}
                    {% for field in form %}
                        {% for error in field.errors %}
                            <span class="btn btn-danger open-sans-600">{{ error|escape }}</span>
                        {% endfor %}
                    {% endfor %}
                    {% for error in form.non_field_errors %}
                        <span class="btn btn-danger open-sans-600">{{ error|escape }}</span>
                    {% endfor %}
                {% endif %}

                <div class="form-group">
                    <label for="id_username" class="col-sm-2 col-form-label open-sans-600">Логин</label>
                    <input type="text" name="username" autofocus="" autocapitalize="none" autocomplete="username" maxlength="150" required="" id="id_username" class="form-control open-sans-500" value="{{ User2.user.username }}" readonly>
                </div>
                <div class="form-group">
                    <label for="id_username" class="col-sm-2 col-form-label open-sans-600">Почта</label>
                    <input type="text" name="email" autofocus="" autocapitalize="none" autocomplete="email" maxlength="150" required="" id="id_email" class="form-control open-sans-500" value="{{ User2.user.email }}">
                </div>
                <div class="form-group">
                    <label for="id_password" class="col-sm-2 col-form-label open-sans-600">Имя</label>
                    <input type="text" name="first_name" autofocus="" autocapitalize="none" autocomplete="first_name" maxlength="150" required="" id="id_first_name" class="form-control open-sans-500" value="{{ User2.first_name }}">
                </div>
                <div class="form-group">
                    <label for="id_password" class="col-sm-2 col-form-label open-sans-600">Фамилия</label>
                    <input type="text" name="last_name" autofocus="" autocapitalize="none" autocomplete="last_name" maxlength="150" required="" id="id_last_name" class="form-control open-sans-500" value="{{ User2.last_name }}">
                </div>
                <div class="form-group">
                    <label for="id_password" class="col-sm-2 col-form-label open-sans-600">Возраст</label>
                    <input type="text" name="age" autofocus="" autocapitalize="none" autocomplete="age" maxlength="150" required="" id="id_age" class="form-control open-sans-500" value="{{ User2.age }}">
                </div>
                <div class="form-group">
                    <label for="id_password" class="col-sm-2 col-form-label open-sans-600">Место работы</label>
                    <input type="text" name="work" autofocus="" autocapitalize="none" autocomplete="work" maxlength="150" required="" id="id_work" class="form-control open-sans-500" value="{{ User2.work }}">
                </div>
                <div class="form-group">
                    <label for="id_password" class="col-sm-2 col-form-label open-sans-600">Должность</label>
                    <input type="text" name="special" autofocus="" autocapitalize="none" autocomplete="special" maxlength="150" required="" id="id_special" class="form-control open-sans-500" value="{{ User2.special }}">
                </div>
                <div class="form-group">
                    <label for="id_password" class="col-sm-2 col-form-label open-sans-600">Статус</label>
                    <input type="text" name="status" autofocus="" autocapitalize="none" autocomplete="status" maxlength="150" required="" id="id_status" class="form-control open-sans-500" value="{{ User2.status }}" readonly>
                </div>
                
                <div class="form-group submit">
                    <button type="submit" class="btn btn-primary  open-sans-600">Подтвердить</button>
                    <a class="btn btn-outline-success  open-sans-600" href="{% url 'profile' %}" role="button">Отмена</a>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

onec/templates/index.html
<!DOCTYPE html>
<html>
    <head>
        <title>{% block title %}{% endblock %}</title>
        {% load static %}
        <link type="text/css" rel="stylesheet" href="{% static 'css/main.css' %}">
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Jaini+Purva&family=Open+Sans:ital,wght@0,300..800;1,300..800&display=swap" rel="stylesheet">
    </head>
    <body>
        <header>
            <div class="head">
                <div class="menu">
                    <h7 class="logo jaini-purva-regular">1C</h7>
                    <a href="{% url 'main' %}" class="menu_button open-sans-500">Главная</a>
                    <a href="{% url 'spravochnik' %}" class="menu_button open-sans-500">Справочник</a>
                    <a href="{% url 'modul' %}" class="menu_button open-sans-500">Модуль</a>
                    <a href="{% url 'onec' %}" class="menu_button open-sans-500">1С?</a>
                    <a href="{% url 'onec_special' %}" class="menu_button open-sans-500">1С:Специалист</a>
                </div>
                <div class="menu_icons">
                    <a href="#"><svg xmlns="http://www.w3.org/2000/svg" height="32px" viewBox="0 -960 960 960" width="32px" fill="#FFCC40"><path d="M280-80q-33 0-56.5-23.5T200-160q0-33 23.5-56.5T280-240q33 0 56.5 23.5T360-160q0 33-23.5 56.5T280-80Zm400 0q-33 0-56.5-23.5T600-160q0-33 23.5-56.5T680-240q33 0 56.5 23.5T760-160q0 33-23.5 56.5T680-80ZM246-720l96 200h280l110-200H246Zm-38-80h590q23 0 35 20.5t1 41.5L692-482q-11 20-29.5 31T622-440H324l-44 80h480v80H280q-45 0-68-39.5t-2-78.5l54-98-144-304H40v-80h130l38 80Zm134 280h280-280Z"/></svg></a>
                    {% if not User %}
                        <a href="{% url 'login' %}"><svg xmlns="http://www.w3.org/2000/svg" height="32px" viewBox="0 -960 960 960" width="32px" fill="#FFCC40"><path d="M480-480q-66 0-113-47t-47-113q0-66 47-113t113-47q66 0 113 47t47 113q0 66-47 113t-113 47ZM160-160v-112q0-34 17.5-62.5T224-378q62-31 126-46.5T480-440q66 0 130 15.5T736-378q29 15 46.5 43.5T800-272v112H160Zm80-80h480v-32q0-11-5.5-20T700-306q-54-27-109-40.5T480-360q-56 0-111 13.5T260-306q-9 5-14.5 14t-5.5 20v32Zm240-320q33 0 56.5-23.5T560-640q0-33-23.5-56.5T480-720q-33 0-56.5 23.5T400-640q0 33 23.5 56.5T480-560Zm0-80Zm0 400Z"/></svg></a>
                    {% else %}
                        <a href="{% url 'profile' %}"><svg xmlns="http://www.w3.org/2000/svg" height="32px" viewBox="0 -960 960 960" width="32px" fill="#FFCC40"><path d="M234-276q51-39 114-61.5T480-360q69 0 132 22.5T726-276q35-41 54.5-93T800-480q0-133-93.5-226.5T480-800q-133 0-226.5 93.5T160-480q0 59 19.5 111t54.5 93Zm246-164q-59 0-99.5-40.5T340-580q0-59 40.5-99.5T480-720q59 0 99.5 40.5T620-580q0 59-40.5 99.5T480-440Zm0 360q-83 0-156-31.5T197-197q-54-54-85.5-127T80-480q0-83 31.5-156T197-763q54-54 127-85.5T480-880q83 0 156 31.5T763-763q54 54 85.5 127T880-480q0 83-31.5 156T763-197q-54 54-127 85.5T480-80Zm0-80q53 0 100-15.5t86-44.5q-39-29-86-44.5T480-280q-53 0-100 15.5T294-220q39 29 86 44.5T480-160Zm0-360q26 0 43-17t17-43q0-26-17-43t-43-17q-26 0-43 17t-17 43q0 26 17 43t43 17Zm0-60Zm0 360Z"/></svg></a>
                        <form action="{% url 'logout' %}" method="POST">
                            {% csrf_token %}
                        <button type="submit" href="{% url 'logout' %}"><svg xmlns="http://www.w3.org/2000/svg" height="32px" viewBox="0 -960 960 960" width="32px" fill="#FFCC40"><path d="M200-120q-33 0-56.5-23.5T120-200v-560q0-33 23.5-56.5T200-840h280v80H200v560h280v80H200Zm440-160-55-58 102-102H360v-80h327L585-622l55-58 200 200-200 200Z"/></svg>
                        </button>
                        </form>
                    {% endif %}
                </div>
            </div>
        </header>
            <div class="wrapper">
        {% block content %}
        {% endblock %}
                <div class="push"></div>
            </div>
            
        <footer class="open-sans-600">
            Lebedkov Maxim
        </footer>
    </body>
    {% block scripts %}{% endblock %}
</html>

onec/templates/main_page.html
{% extends "index.html" %}

{% block title %}Главная страница{% endblock %}

{% block content %}
{% load static %}
<div class="content">
    <img src="{% static 'img/banner.png' %}" class="banner"/>
    <div class="render">
        <div class="banner_one" onclick="goToPage('guide')">
            <p class="banner_one_text open-sans-600">Полный справочник по 1С:Предприятие</p>
            <img src="{% static 'img/knigi.png' %}" class="knigi"/>
        </div>
        <div class="banner_two" onclick="goToPage('modul')">
            <p class="banner_two_text open-sans-600">Планирование заказов на поставку</p>
            <img src="{% static 'img/fura.png' %}" class="knigi"/>
        </div>
    </div>

    <div class="plates">
        <div class="buttons_plate_cl">
            <div class="buttons_plate_rw">
                <div class="block_one" onclick="goToPage('onec')">
                    <div class="icon">
                        <svg xmlns="http://www.w3.org/2000/svg" height="32px" viewBox="0 -960 960 960" width="32px" fill="#CB0B0B"><path d="m480-123.34-46.56-43.17q-107.54-99.7-176.52-169.57-68.97-69.87-108.75-123.1-39.78-53.23-54.64-96.67-14.86-43.44-14.86-87.94 0-90.26 62.28-152.24Q203.22-858 293.79-858q51.36 0 99.72 25.1 48.36 25.11 86.49 73.16 40.44-48.87 87.89-73.57Q615.34-858 666.21-858q90.57 0 152.84 61.97 62.28 61.98 62.28 152.24 0 44.5-14.86 87.94t-54.61 96.61q-39.75 53.18-108.69 123.11-68.94 69.92-176.61 169.62L480-123.34Zm0-91.12q99.81-91.32 164.41-156.01 64.61-64.7 102.23-113.13 37.62-48.43 52.36-85.89 14.74-37.46 14.74-74.38 0-62.98-41.57-104.76-41.58-41.78-105.82-41.78-48.55 0-91.21 29.82-42.65 29.82-65.14 79.26h-60.41q-22.46-49.16-65.38-79.12-42.92-29.96-90.56-29.96-63.86 0-105.62 41.59-41.77 41.59-41.77 105.32 0 36.71 14.78 74.31 14.79 37.6 52.57 85.85 37.77 48.26 102.13 112.99Q380.1-305.62 480-214.46Zm0-288.31Z"/></svg>
                    </div>
                    <div class="text_main">     
                        <span class="block_main_text open-sans-600">Что такое 1С?</span>
                    </div>
                </div>
                <div class="block_one" onclick="goToPage('modul')">
                    <div class="icon">
                        <svg xmlns="http://www.w3.org/2000/svg" height="32px" viewBox="0 -960 960 960" width="32px" fill="#1BCB0B"><path d="M45.28-84.93v-803.99h435.13v183.64h434.31v620.35H45.28Zm67.59-67.58h116.31v-116.31H112.87v116.31Zm0-183.9h116.31v-116.05H112.87v116.05Zm0-184.97h116.31v-116.31H112.87v116.31Zm0-183.9h116.31v-116.05H112.87v116.05Zm183.9 552.77h116.05v-116.31H296.77v116.31Zm0-183.9h116.05v-116.05H296.77v116.05Zm0-184.97h116.05v-116.31H296.77v116.31Zm0-183.9h116.05v-116.05H296.77v116.05Zm183.64 552.77h366.72v-485.18H480.41v116.31h91.69v67.58h-91.69v117.39h91.69v67.59h-91.69v116.31ZM670.77-453.8v-67.58h67.59v67.58h-67.59Zm0 184.98v-67.59h67.59v67.59h-67.59Z"/></svg>
                    </div>
                    <div class="text_main">     
                        <span class="block_main_text open-sans-600">Кому подойдет модуль?</span>
                    </div>
                </div>
                <div class="block_one" onclick="goToPage('onec_special')">
                    <div class="icon">
                        <svg xmlns="http://www.w3.org/2000/svg" height="40px" viewBox="0 -960 960 960" width="40px" fill="#FF7017"><path d="M162.57-164q-32.52 0-56.21-23.69-23.69-23.7-23.69-56.21v-472.2q0-32.51 23.69-56.21Q130.05-796 162.57-796h634.86q32.52 0 56.21 23.69 23.69 23.7 23.69 56.21v472.2q0 32.51-23.69 56.21Q829.95-164 797.43-164H162.57Zm0-67.59h634.86q4.62 0 8.47-3.85 3.84-3.84 3.84-8.46v-402.61H150.26v402.61q0 4.62 3.84 8.46 3.85 3.85 8.47 3.85ZM300-288.18l-47-46.74 103-104-104-104 48-47 151 151-151 150.74Zm186.54 2.72v-67.59h227.59v67.59H486.54Z"/></svg>
                    </div>
                    <div class="text_main">         
                        <span class="block_main_text open-sans-600">1С:Специалист</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
    
</div>

{% block script %}
<script>
    function goToPage(link) {
        window.location.href = 'https://sitekpk.pythonanywhere.com/'+link;
    }
</script>
{% endblock %}

{% endblock %}

onec/templates/modul.html
{% extends 'index.html' %}

{% block title %}Модуль{% endblock %}

{% block content %}
    <div class="content">
        <div class="body">
            <div class="zag open-sans-700">
                Модуль планирования заказов на поставку
            </div>
            <div class="flexible">
                <div class="left_side open-sans-600">
                    <p>Данный продукт будет разрабатываться для размещения на сервере компании, а также будет ориентирован на планирование заказов на закупку на предприятие. В отличие от облачных решений, модуль не требует постоянного подключения к внешним системам или сложных настроек для работы, что снижает стоимость и делает его более доступным.</p>
                    <p>Потенциальными пользователями модуля являются средний и крупный бизнес, для которых необходимо решать вопросы с наличием неликвидных запасов и для которых остановка производственной деятельности является критичной из-за отсутствия необходимых материалов.</p>
                    <p>В состав поставки входят:</p>
                    <p>1. Продукт предусматривает возможность установки на сервер компании, что обеспечивает гибкость и независимость от сторонних облачных сервисов.</p>
                    <p>2. Техническая документация с инструкциями по установке и использованию. Модуль будет размещён на сервере компании, а установку продукта проведёт сотрудник компании с использованием предоставленного установочного пакета, либо IT-отделом.</p>
                </div>
                <div class="right_side">
                    {% load static %}
                    <img src="{% static 'img/oneclogo.png' %}" style="width: 100%;"/>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block scripts %}

{% endblock %}

onec/templates/profile.html
{% extends 'index.html' %}

{% block content %}

<div class="content">
    <div class="body">
        <div class="zag open-sans-600">
            Личный кабинет
        </div>
        <div class="cong">
            <div class="profile">
                <div class="photo">
                    {% load static %}
                    <img src="{% static 'img/profile.jpg' %}" style="width: 140px; height: 140px; border-radius: 50%; border: 2px #CB5413 solid;"/>
                </div>
                <div class="data">
                    <div class="col">
                        <div class="profile_name open-sans-500">
                            {{ User2.first_name }} {{ User2.last_name }} <a href="{% url 'edit' %}" class="edit_text open-sans-500">Редактировать</a>
                        </div>
                        <div class="row">
                            <div class="col">
                                <div class="profile_age open-sans-500">
                                    Возраст: {{ User2.age }}
                                </div>
                                <div class="profile_status open-sans-500">
                                    Статус: {{ User2.status }}
                                </div>
                            </div>
                            <div class="col">
                                <div class="profile_work open-sans-500">
                                    Место работы: {{ User2.work }}
                                </div>
                                <div class="profile_special open-sans-500">
                                    Должность: {{ User2.special }}
                                </div>
                            </div>
                        </div>            
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}